[package]
name = "tcp-file-encoded-transfer"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.2"
serde = { version = "1.0.223", features = ["derive"] }
serde_json = "1.0.145"
tungstenite = "0.27.0"
